name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Build release artifacts
        run: zig build release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: zig-out/archives/*
          generate_release_notes: true
